export const defaultEventCodes = [
    { code: "WD", name: "HOLD FOR WEIGHT DIFF", Tag: "WD" },
    { code: "CL", name: "HOLD FOR CREDIT LIMIT", Tag: "CL" },
    { code: "RA", name: "HOLD FOR REMOTE AREA", Tag: "RA" },
    { code: "OS", name: "HOLD FOR OVERSIZE", Tag: "OS" },
    { code: "OV", name: "HOLD FOR OVERWEIGHT", Tag: "OV" },
    { code: "BC", name: "HOLD FOR BAD CONTENT", Tag: "BC" },
    { code: "IN", name: "HOLD FOR INVOICE", Tag: "IN" },
    { code: "KY", name: "HOLD FOR KYC", Tag: "KY" },
    { code: "H", name: "HOLD FOR SERVICE", Tag: "1" },
    { code: "22", name: "FEDEX PAPER WORK MISSING", Tag: "22" },
    { code: "25", name: "RETURNED FROM DHL DUE TO IMAGE MISSING", Tag: "25" },
    { code: "26", name: "RETURNED FROM DHL DUE TO BROKEN CONTENT", Tag: "26" },
    { code: "28", name: "RETURNED FROM DHL DUE TO IMAGE MISSING", Tag: "28" },
    { code: "29", name: "RETURNED FROM DHL DUE TO DG BOX", Tag: "29" },
    { code: "OF02", name: "PKT OFFLOAD BY DELHI CUSTOMS", Tag: "OOF2" },
    { code: "30", name: "HOLD DUE TO OVER SIZE", Tag: "30" },
    { code: "36", name: "NEED C/NEE ID AND INVOICE WITH HSN CODE", Tag: "36" },
    { code: "37", name: "RETURNED DUE TO TYPE OF SHIPPING BILL", Tag: "37" },
    { code: "41", name: "QUANTITY MISSMATCH", Tag: "41" },
    { code: "45", name: "GST JEWELLERY PURCHASE BILL REQ", Tag: "45" },
    { code: "60", name: "NON DG REQ", Tag: "60" },
    { code: "61", name: "25+ WT NOT ACCEPTABLE FOR USA", Tag: "61" },
    { code: "8", name: "HOLD FOR EXTRA WT", Tag: "HEW" },
    { code: "TNT", name: "RETURN FROM TNT DUE TO CONTENT MISMATCH", Tag: "TNT" },
    { code: "102", name: "HOLD FOR CONSIGNEE INCOMPLETE ADDRESS", Tag: "102" },
    { code: "CPC", name: "Completed customs clearance process", Tag: "CPC" },
    { code: "77", name: "INVOICE & AWB MISMATCH ADD", Tag: "77" },
    { code: "BROK", name: "BROKEN CONTENT", Tag: "1" },
    { code: "ADD", name: "ADDRESS CHANGE", Tag: "ADD" },
    { code: "SN", name: "STONE NOT ALLOWED IN USA", Tag: "SN" },
    { code: "QATA", name: "C/NEE ID REQ FOR QATAR", Tag: "QATA" },
    { code: "TEL", name: "TELEPHONE BILL REQ", Tag: "TEL" },
    { code: "10", name: "INCOMPLETE KYC", Tag: "0" },
    { code: "4554", name: "HSN CODE INVOICE REQ", Tag: "4554" },
    { code: "454", name: "HOLD FOR HIGH VALUE", Tag: "454" },
    { code: "L", name: "HOLD FOR HEAD LIGHT", Tag: "A" },
    { code: "G", name: "HOLD FOR GOGGLES", Tag: "A" },
    { code: "DLJM", name: "DELIVERED TO CONSIGNEE AT JAMAICA NEWYORK", Tag: "DLJM" },
    { code: "IOSS", name: "HOLD FOR IOSS NUMBER", Tag: "IOSS" },
    { code: "541", name: "HOLD FOR SERVICE BDDHL NOT CAPTUR", Tag: "141" },
    { code: "EALR", name: "ELECTRONIC AUTHORIZATION LETTER REQ", Tag: "222" },
    { code: "OFF", name: "Flight Offload", Tag: "OFF" },
    { code: "222", name: "NEED GST PURCHASE BILL WITH STAMP", Tag: "222" },
    { code: "MISR", name: "MISROUTE(AF# 057-01631722)", Tag: "MISR" },
    { code: "DELS", name: "Delivered to Narinder Singh", Tag: "DELS" },
    { code: "HAC", name: "HANDOVER TO CUSTOM", Tag: "HAC" },
    { code: "JJ", name: "plot no not mention", Tag: "R" },
    { code: "999", name: "ART JEWELLERY NOT ALLOWED", Tag: "AJNA" },
    { code: "E007", name: "PLANING FOR NEXT AVILABLE FLIGHT", Tag: "E007" },
    { code: "SK", name: "Address Incomplete", Tag: "3" },
    { code: "2222", name: "PURCHASE BILL REQ", Tag: "2222" },
    { code: "A&R", name: "alleviated and restricted charges", Tag: "1" },
    { code: "AAAA", name: "undeclared content", Tag: "454" },
    { code: "AS", name: "HOLD FOR AMAZON SHIPMENT", Tag: "AS" },
    { code: "HMS", name: "HOLD DUE TO MULTIPLE SHIPPMENT IN AUSTRALIA", Tag: "2" },
    { code: "YODE", name: "yodel service shipment not forwarded amazon addres", Tag: "15" },
    { code: "5654", name: "C/NEE ID REQ", Tag: "5654" },
    { code: "HYD", name: "HYDERABAD", Tag: "HYD" },
    { code: "LABE", name: "LABEL NOT GENERATE", Tag: "1" },
    { code: "LOST", name: "LOST AT ORIGIN", Tag: "LOST" },
    { code: "SIR", name: "SEARCH IN OFFICE", Tag: "SIR" },
    { code: "74", name: "NEED DHL AUTHORITY LETTER", Tag: "74" },
    { code: "456", name: "SERVICE NOT AVAILABLE IN GIVEN ZIP CODE", Tag: "ABC" },
    { code: "3", name: "HOLD FOR ELECTRONIC ITEM", Tag: "5" },
    { code: "2", name: "HOLD FOR PERFUME NOT ALLOWED", Tag: "1" },
    { code: "WOOD", name: "HOLD FOR WOODEN ITEM", Tag: "1" },
    { code: "WDL", name: "wooden declaration letter", Tag: "2" },
    { code: "5", name: "invoice & shipment addresh mismatch address", Tag: "1" },
    { code: "STAR", name: "HOLD AS PER STARLINE MUM", Tag: "12" },
    { code: "RATE", name: "HOLD FOR RATES NOT UPDATED", Tag: "23" },
    { code: "DAMG", name: "HOLD FOR DAMAGE ITEM", Tag: "F" },
    { code: "GH", name: "HOLD FOR GHEE", Tag: "GH" },
    { code: "FDF", name: "Hold for invoice & shipment Add mismatch address", Tag: "HOLD" },
    { code: "333", name: "HOLD DUE TO SILVER ITEM", Tag: "55" },
    { code: "31", name: "RFT DUE TO QUANTITY MISMATCH", Tag: "31" },
    { code: "32", name: "HOLD FOR MSDS", Tag: "32" },
    { code: "33", name: "VALUE MISMATCH OF WATCH PURCHASE BILL", Tag: "33" },
    { code: "38", name: "GOOGLES NOT ALLOWD IN USA", Tag: "38" },
    { code: "MSCH", name: "MISROUTE AND CUSTOM HOLD", Tag: "MSCH" },
    { code: "40", name: "ITEM MISMATCH", Tag: "40" },
    { code: "42", name: "INVOICE VALUE MISMATCH", Tag: "42" },
    { code: "50", name: "HOLD FOR DHL AUTHORITY LETTER", Tag: "50" },
    { code: "SS", name: "HOLD FOR SERVICE SUSPENDED", Tag: "SS" },
    { code: "MAIL", name: "HOLD FOR RECEIVER MAIL ID IN INVOICE", Tag: "MAIL" },
    { code: "754", name: "JEWELLERY LETTER REQ", Tag: "754" },
    { code: "1", name: "COMMERCIAL QUANTITY", Tag: "1" },
    { code: "MUL1", name: "TWO PKT SAME RECEIVED", Tag: "MULT" },
    { code: "DR", name: "NEED CHEMIST BILL", Tag: "DR" },
    { code: "T", name: "TEMPORARY SERVICE NOT AVAILABLE IN GIVEN ZIP CODE", Tag: "F" },
    { code: "BN", name: "BOOK NAME REQ", Tag: "BN" },
    { code: "125", name: "INCOMPLETE CONSIGNEE ADDRESS", Tag: "125" },
    { code: "MIS", name: "FLIGHT MISROUTE", Tag: "MIS" },
    { code: "151", name: "HOLD INVOICE MISMATCH", Tag: "151" },
    { code: "3RD", name: "Handed over to 3rd party for final delivery", Tag: "3RD" },
    { code: "ADI", name: "Address Incorrect", Tag: "EX" },
    { code: "APPR", name: "CHECK LIST SENT FOR APPROVAL", Tag: "APPR" },
    { code: "AR", name: "Arrived At Location", Tag: "AR" },
    { code: "CAI", name: "Cnee Address Incorrect", Tag: "CAI" },
    { code: "CC", name: "DLVRY ATMPD CNEE CLOSED", Tag: "CC" },
    { code: "CCC", name: "Customs Clearance Completed", Tag: "CCC" },
    { code: "CCD", name: "Custom Clearance Delay", Tag: "CCD" },
    { code: "CDD", name: "Clearance delay at Delhi", Tag: "CDD" },
    { code: "CDNR", name: "CSB Documents Not Received", Tag: "CDNR" },
    { code: "CHA", name: "CHECK LIST APPROVED", Tag: "CHA" },
    { code: "CHF", name: "Check List Filed", Tag: "CHF" },
    { code: "CI", name: "Held in Customs for Consignees Instructions", Tag: "CI" },
    { code: "CNA", name: "Cnee Not Available", Tag: "CNA" },
    { code: "CNL", name: "C.nee Not Located", Tag: "CNL" },
    { code: "CNM", name: "Contact no missing", Tag: "CNM" },
    { code: "CP", name: "Custom clearance in progress", Tag: "CP" },
    { code: "CR", name: "Hold for credit limit", Tag: "CR" },
    { code: "CRD", name: "Cnee Refused Delivery", Tag: "CRD" },
    { code: "CS", name: "Consignee Shifted", Tag: "CS" },
    { code: "CUP", name: "Checklist Under Process", Tag: "CUP" },
    { code: "DL", name: "Delivered", Tag: "DL" },
    { code: "DLVD", name: "DELIVERED TO CONSIGNEE", Tag: "DLVD" },
    { code: "DUTY", name: "DUTY PAYMENT AWAITED", Tag: "DUTY" },
    { code: "ED", name: "Expected to depart", Tag: "ED" },
    { code: "EDT", name: "ESTIMATED DELIVERY TOMORROW", Tag: "EDT" },
    { code: "EFN", name: "Economy Flight Not Available", Tag: "EFN" },
    { code: "EXP", name: "Expected Arrival at Destination", Tag: "EXP" },
    { code: "FMR", name: "Flight Misrouted In Transit", Tag: "FMR" },
    { code: "HAL", name: "HAND OVER TO AIRLINES", Tag: "HAL" },
    { code: "HAND", name: "HOLD FOR HANDLING CHARGES", Tag: "HAND" },
    { code: "HBC", name: "Hold due to Bad Contents", Tag: "HBC" },
    { code: "HBP", name: "Hold due to Bad Packing", Tag: "HBP" },
    { code: "HC", name: "Held in customs for consignee instructions", Tag: "HC" },
    { code: "HCD", name: "Held in Customs at Destination", Tag: "HCD" },
    { code: "HCDC", name: "Held in Delhi Customs", Tag: "HCDC" },
    { code: "HCNA", name: "Hold due to contents not allowed", Tag: "HCNA" },
    { code: "HCP", name: "Held for Consignee Pick Up", Tag: "HCP" },
    { code: "HCPW", name: "Hold for Commercial Paperwork", Tag: "HCPW" },
    { code: "HDC", name: "Hold due to Custom Problem", Tag: "HDC" },
    { code: "HDP", name: "HOLD DUE TO NON PAYMENT", Tag: "HDP" },
    { code: "HDT", name: "Held in custom for Duty \u0026 Taxes", Tag: "HDT" },
    { code: "HFA", name: "Hold for Address", Tag: "HFA" },
    { code: "HFDT", name: "HELD FOR DUTY/TAXES", Tag: "HFDT" },
    { code: "HFK", name: "HOLD FOR KYC", Tag: "HFK" },
    { code: "HHP", name: "Hold at Delhi Hub for Payment", Tag: "HHP" },
    { code: "HIK", name: "Hold for invoice and KYC", Tag: "HIK" },
    { code: "HMSU", name: "Hold due to Multiple shipment to Europe", Tag: "HMSU" },
    { code: "HNAD", name: "Hold for NOC from ADC", Tag: "HNAD" },
    { code: "HOD", name: "Hold Due to Payment", Tag: "HOD" },
    { code: "HOR", name: "Hold for other reasons", Tag: "HOR" },
    { code: "HOS", name: "Hold Due to Service", Tag: "HOS" },
    { code: "HP", name: "Shipment Hold- Paperwork Missing", Tag: "HP" },
    { code: "HPSR", name: "Hold as per Shipper Request", Tag: "HPSR" },
    { code: "HRA", name: "Hold due to Remote Area", Tag: "HRA" },
    { code: "HRI", name: "Hold due to revised invoice required", Tag: "HRI" },
    { code: "HSC", name: "Hold for service confirmation", Tag: "HSC" },
    { code: "HSR", name: "Hold as per Shipper Request", Tag: "HSR" },
    { code: "HTNT", name: "Hold for TNT paperwork", Tag: "HTNT" },
    { code: "HTP", name: "Handed over to 3rd party for final delivery", Tag: "HTP" },
    { code: "HUB", name: "Shipment Received At Hub", Tag: "HUB" },
    { code: "HWD", name: "Hold due to Weight Difference", Tag: "HWD" },
    { code: "IN", name: "Inscan at hub", Tag: "IN" },
    { code: "INB", name: "Inscan at branch", Tag: "INB" },
    { code: "INCO", name: "INCORECT ADDRESS", Tag: "INCO" },
    { code: "IT", name: "In Transit", Tag: "IT" },
    { code: "LA", name: "Late Arrived", Tag: "LA" },
    { code: "LEFA", name: "Shipment left from Ahmedabad", Tag: "LEFA" },
    { code: "LEFD", name: "LEFT FROM DELHI", Tag: "LEFD" },
    { code: "LEFT", name: "Shipment left from hub", Tag: "LEFT" },
    { code: "LFD", name: "LEFT FROM DELHI", Tag: "LFD" },
    { code: "OF", name: "Shipment OffLoad", Tag: "OF" },
    { code: "OUT", name: "Out for Delivery", Tag: "OUT" },
    { code: "PCAM", name: "Pls contact your A/c Sales Manager", Tag: "PCAM" },
    { code: "PCCS", name: "Pls contact Customer Service", Tag: "PCCS" },
    { code: "PFC", name: "Pending for Console", Tag: "PFC" },
    { code: "RACT", name: "Received after cut off time", Tag: "RACT" },
    { code: "RC", name: "Released from Customs", Tag: "RC" },
    { code: "NA", name: "HOLD FOR AMOUNT NOT CAPTURE", Tag: "NA" },
    { code: "EC", name: "HOLD FOR EXTRA CHARGES", Tag: "EC" },
    { code: "RTC", name: "Return to Overseas Office", Tag: "RTC" },
    { code: "RTO", name: "Return to Origin", Tag: "RTO" },
    { code: "SBF", name: "Shipping Bill Filed", Tag: "SBF" },
    { code: "SBP", name: "SHIPPING BILL PENDING IN CUSTOMS", Tag: "SBP" },
    { code: "SBR", name: "Shipping Bill Recieved", Tag: "SBR" },
    { code: "SR", name: "Shipment information received", Tag: "SR" },
    { code: "UC", name: "Under Clearance", Tag: "UC" },
    { code: "UL", name: "Unable to Locate", Tag: "UL" },
    { code: "WZ", name: "Wrong Zipcode", Tag: "WZ" },
    { code: "HI", name: "Hold for Invoice", Tag: "HI" },
    { code: "HE", name: "Hold for Extra Charges", Tag: "HE" },
    { code: "AD", name: "Appointment Delivery", Tag: "AD" },
    { code: "HD", name: "Held For Documentations", Tag: "HD" },
    { code: "CCU", name: "CALCUTTA", Tag: "CCU" },
    { code: "CAL", name: "CALCUTTA", Tag: "CAL" },
    { code: "HA", name: "Handover to Airline", Tag: "HA" },
    { code: "OFD", name: "OUT FOR DELIVERY", Tag: "OFD" },
    { code: "SSOC", name: "SHIPMENT SEIZED IN OVERSEAS CUSTOM", Tag: "SSOC" },
    { code: "RAA", name: "Re-assign to airline", Tag: "RAA" },
    { code: "ZCOD", name: "ZIP CODE NOT MENTIONED", Tag: "ZCOD" },
    { code: "CD", name: "Connections Done", Tag: "CD" },
    { code: "FDR", name: "Future Delivery Requested by c/nee", Tag: "FDR" },
    { code: "DTP", name: "Duty/Taxes payment received", Tag: "DTP" },
    { code: "ECD", name: "Expected connections done", Tag: "ECD" },
    { code: "P", name: "HOLD DUE TO PACKET NOT RECEIVED", Tag: "P" },
    { code: "KTM", name: "KATHMANDU", Tag: "KTM" },
    { code: "NPL", name: "NEPAL", Tag: "NPL" },
    { code: "DC", name: "Delay Connections", Tag: "DC" },
    { code: "D", name: "INVOICE \u0026 PKT ADDRESS DIFFRENT", Tag: "D" },
    { code: "FD", name: "FLIGHT DELAY", Tag: "FD" },
    { code: "HIC", name: "HELD IN CUSTOMS", Tag: "HIC" },
    { code: "AC", name: "ACCOUNT DEACTIVATED", Tag: "AC" },
    { code: "IFD", name: "INTRANSIT TO FINAL DESTINATION", Tag: "IFD" },
    { code: "NRB", name: "NAIROBI", Tag: "NRB" },
    { code: "HAM", name: "HOLD AS PER MANDEEP SIR", Tag: "HAM" },
    { code: "I", name: "HOLD FOR ITALY", Tag: "I" },
    { code: "ITAL", name: "HOLD FOR ITALY", Tag: "ITAL" },
    { code: "HAN", name: "HOLD FOR MEDICINE", Tag: "HAN" },
    { code: "O", name: "HOLD FOR OVER WTT", Tag: "O" },
    { code: "HSM", name: "HOLD FOR SIGNATURE MISMATCH", Tag: "HSM" },
    { code: "HFS", name: "HOLD FOR SHIPPER SIGNATURE", Tag: "HFS" },
    { code: "PKT", name: "PKT NOT RECEIVED", Tag: "PKT" },
    { code: "C", name: "HOLD FOR COSMETIC ITEM", Tag: "C" },
    { code: "11", name: "HOLD FOR INOVICE \u0026 AWB MISMATCH ADD", Tag: "11" },
    { code: "CSBE", name: "CSB EXCEL FILE NOT RECEIVED", Tag: "CSBE" },
    { code: "CSBI", name: "CSB PDF INVOICE NOT RECEIVED", Tag: "CSBI" },
    { code: "1", name: "CONSIGNEE NAME NOT MENTION", Tag: "1" },
    { code: "NCON", name: "NEED CONTACT NUMBER", Tag: "NCON" },
    { code: "W", name: "HOLD FOR WRIST WATCH", Tag: "W" },
    { code: "RFD", name: "RETURN FROM DHL DUE TO KYC", Tag: "RFD" },
    { code: "RFDM", name: "RETURN FROM DHL DUE TO KYC MISMATCH", Tag: "RFDM" },
    { code: "OV", name: "HOLD FOR OVER SIZE", Tag: "OV" },
    { code: "B", name: "HOLD FOR BRANDED ITEMS", Tag: "B" },
    { code: "PA", name: "HOLD FOR PROTEIN POWDER", Tag: "PA" },
    { code: "CODC", name: "COD CONFIRMATION", Tag: "CODC" },
    { code: "APT", name: "APT NUMBER MISSING", Tag: "APT" },
    { code: "SUIT", name: "HOLD DUE TO MISSING SUITE NUMBER", Tag: "SUIT" },
    { code: "HOLD", name: "HOLD FOR TABACCO", Tag: "HOLD" },
    { code: "UTS", name: "HOLD DUE TO HERBAL ITEM", Tag: "UTS" },
    { code: "78", name: "Hold for lable not inscan \u0026 awb not mention on par", Tag: "78" },
    { code: "855", name: "HOLD DUE TO PO BOX ADDRESS", Tag: "855" },
    { code: "I001", name: "INCOMPLETE INVOICE", Tag: "I001" },
    { code: "K001", name: "KYC NOT CLEAR", Tag: "K001" },
    { code: "2", name: "PLS NOT FORWERD THIS SHIPMENT AS PER SHIPPER REQUE", Tag: "2" },
    { code: "PUR", name: "NEED PURCHASE BILL FOR WATCH", Tag: "PUR" },
    { code: "HFAL", name: "HOLD DUE TO AUTHORITY LETTER", Tag: "HFAL" },
    { code: "AUTH", name: "HOLD FOR AUTH LATTER", Tag: "AUTH" },
    { code: "SALS", name: "HOLD AS PER SALES PERSON", Tag: "SALS" },
    { code: "EXC", name: "Expected Connection", Tag: "EXC" },
    { code: "PBR", name: "RETURNED FROM DHL DUE TO ADDRESS MISSMATCH", Tag: "PBR" },
    { code: "KM", name: "RETURNED FROM DHL DUE TO KYC MISMATCH", Tag: "KM" },
    { code: "RA", name: "HOLD DUE TO REMOTE AREA IN FEDEX", Tag: "RA" },
    { code: "ND", name: "NEED NON DG LETTER REQ", Tag: "ND" },
    { code: "WATC", name: "HOLD FOR WATCH PURCHASE BILL", Tag: "WATC" },
    { code: "RRR", name: "RETURNED FROM DHL DUE INVOICE AND KYC", Tag: "RRR" },
    { code: "IM", name: "RETURNED FROM DHL DUE TO IMAGE MISSING", Tag: "IM" },
    { code: "HFKN", name: "HOLD FOR KYC NOT CLEAR", Tag: "HFKN" },
    { code: "NAR", name: "RETURNED FROM DHL DUE TO NON ANTIQUE LETTER REQ", Tag: "NAR" },
    { code: "IMR", name: "HOLD FOR INVOICE MADE UP REQ", Tag: "IMR" },
    { code: "CQ", name: "HOLD FOR COMMERCIAL QUANTITY", Tag: "CQ" },
    { code: "RFDI", name: "RETURNED FROM DHL DUE TO INVOICE REQ", Tag: "RFDI" },
    { code: "JPBR", name: "HOLD FOR JEWELLERY PURCHASE BILL REQ", Tag: "JPBR" },
    { code: "54", name: "INVOICE MADE UP REQ", Tag: "54" },
    { code: "4", name: "HOLD FOR FUMIGATION CERTIFICATE", Tag: "4" },
    { code: "HRC", name: "HOLD FOR COUNTRY MISMATCH", Tag: "HRC" },
    { code: "14", name: "(AUSTRALIA)LEATHER ITEM NOT ALLOWED IN FEDEX", Tag: "14" },
    { code: "CSIV", name: "CSB V invoice not received", Tag: "CSIV" },
    { code: "WPC", name: "RETURNED FROM DHL DUE WRONG PRODUCT CODE", Tag: "WPC" },
    { code: "1", name: "INCOMPLETE SHIPPER ADDRESS", Tag: "1" },
    { code: "6", name: "PEN NOT ALLOWED IN FEDEX", Tag: "6" },
    { code: "9", name: "HOLD FOR SHIPPER NO NOT MENTIONED ON INVOICE", Tag: "9" },
    { code: "INVO", name: "HOLD INVOICE AND KYC", Tag: "INVO" },
    { code: "15", name: "(AUSTRALIA)BOOKS NOT ALLOWED IN FEDEX", Tag: "15" },
    { code: "MOU", name: "HELD FOR MOU DOCUMENTATIONS", Tag: "MOU" },
    { code: "SD", name: "Schedule Delivery", Tag: "SD" },
    { code: "H", name: "HOLD FOR CH. VOL. WT", Tag: "H" },
    { code: "M", name: "HOLD FOR MEDICINE", Tag: "M" },
    { code: "A", name: "HOLD DUE TO AMOUNT NOT CAPTURE", Tag: "A" },
    { code: "S", name: "HOLD FOR SANITIZER", Tag: "S" },
    { code: "HM", name: "HOLD FOR MEDICINE", Tag: "HM" },
    { code: "OVER", name: "HOLD DUE TO OVER SIZE FDX ENVELOPE", Tag: "OVER" },
    { code: "PB", name: "RETURNED FROM DHL DUE TO PURCHASE BILL REQ", Tag: "PB" },
    { code: "ID", name: "RETURNED FROM DHL DUE TO INCOMPLETE ADDRESS ON INV", Tag: "ID" },
    { code: "AJNA", name: "ART JEWELLERY NOT ALLOWED IN FEDEX", Tag: "AJNA" },
    { code: "HCNM", name: "HOLD FOR HSN CODE NOT MENTIONED ON INVOICE", Tag: "HCNM" },
    { code: "CSBV", name: "CSB V PDF not received", Tag: "CSBV" },
    { code: "ILR", name: "INDEMNITY LETTER REQ", Tag: "ILR" },
    { code: "2", name: "PURCHASE BILL VALUE MISMATCH FROM INVOICE", Tag: "2" },
    { code: "5", name: "HOLD FOR STATUE NOT ALLOWED IN TNT", Tag: "5" },
    { code: "7", name: "HOLD FOR DL AND PAN CARD IN BOX NOT ALLOWED", Tag: "7" },
    { code: "8", name: "HOLD FOR PEN NOT ALLOWED IN TNT", Tag: "8" },
    { code: "13", name: "PEN NOT ALLOWED IN DHL", Tag: "13" },
    { code: "16", name: "CONTENT PROHIBITED", Tag: "16" },
    { code: "17", name: "HOLD FOR CITY INCORRECT", Tag: "17" },
    { code: "18", name: "HOLD FOR PURCHASE BILL MISMATCH", Tag: "18" },
    { code: "20", name: "CONTENT MISMATCH WITH INVOICE", Tag: "20" },
    { code: "21", name: "RETURN FROM DHL DUE TO POWDER", Tag: "21" },
    { code: "PC", name: "HELD FOR PAPER WORK CHECKED BY CUSTOM", Tag: "PC" },
    { code: "DHE", name: "DHE TRUCKING", Tag: "DHE" },
    { code: "NB", name: "NAIROBI", Tag: "NB" },
    { code: "POB", name: "P O BOX ADDRESS", Tag: "POB" },
    { code: "HFAD", name: "HOLD DUE TO JEWELLERY DECLARATION LETTER", Tag: "HFAD" },
    { code: "3", name: "ANTIQUE LETTER REQ", Tag: "3" },
    { code: "E", name: "HOLD FOR EATABLE ITEM", Tag: "E" },
    { code: "AH", name: "ARRIVED HUB", Tag: "AH" },
    { code: "AAA", name: "HOLD DUE TO SIGNATURE REQ ON AUTHORITY LETTER", Tag: "AAA" },
    { code: "1485", name: "HOLD FOR INVOICE \u0026 KYC ADDRESS MISMATCH", Tag: "1485" },
    { code: "R026", name: "REMOTE AREA", Tag: "R026" },
    { code: "10", name: "HOLD FOR INVOICE VALUE MISMATCH", Tag: "10" },
    { code: "12", name: "HOLD FOR INVOICE NOT CLEAR", Tag: "12" },
    { code: "SPIC", name: "HOLD FOR SPICE", Tag: "SPIC" },
    { code: "MR", name: "RETURNED FROM DHL DUE TO MADE UP REQUIRED", Tag: "MR" },
    { code: "BNR", name: "HOLD FOR BOOK NAME REQ", Tag: "BNR" },
    { code: "23", name: "CSV-5 PAPERWORK NEED", Tag: "23" },
    { code: "POA", name: "HOLD FOR POA", Tag: "POA" },
    { code: "US", name: "HOLD AT CUSTOM", Tag: "US" },
    { code: "BT", name: "REMOTE AREA ZIP CODE LABEL NOT GENERATE IN SYSTEM", Tag: "BT" },
    { code: "BGM", name: "Bag Misrouted", Tag: "BGM" },
    { code: "5414", name: "PLZ CONFIRM CSB-V", Tag: "5414" },
    { code: "AMX", name: "Aramex", Tag: "AMX" },
    { code: "CPA", name: "Clearance Pending - Wrong Nomination by Airlines", Tag: "CPA" },
    { code: "SCCP", name: "Shipment Collected By CouriersPlease", Tag: "SCCP" },
    { code: "CLM", name: "Claim issued", Tag: "CLM" },
    { code: "HDTP", name: "Handover to Delivery Partner", Tag: "HDTP" },
    { code: "RD", name: "Ready to Dispatch", Tag: "RD" },
    { code: "BTT", name: "BTT In Process", Tag: "BTT" },
    { code: "ECL", name: "Expected Clearance", Tag: "ECL" },
    { code: "MAN", name: "SHIPMENT MANIFESTED", Tag: "MAN" },
    { code: "AFD", name: "Awaiting Flight Departure", Tag: "AFD" },
    { code: "SM", name: "Shipment Manifested", Tag: "SM" },
    { code: "ITD", name: "In Transit to Destination", Tag: "ITD" },
    { code: "UCC", name: "Under Custom Clearance", Tag: "UCC" },
    { code: "L001", name: "HOLD FOR LIQUID CONTENT", Tag: "L001" },
    { code: "SDDP", name: "Scan Delay by Delivery Partner", Tag: "SDDP" },
    { code: "BMP", name: "Bag Misplaced", Tag: "BMP" },
    { code: "AU", name: "AUS", Tag: "AU" },
    { code: "DEP", name: "Shipment Departed", Tag: "DEP" },
    { code: "UOFD", name: "UNDER OPERATION FACILITY AT DEST.", Tag: "UOFD" },
    { code: "AAC", name: "Awaiting Arrival Confirmation", Tag: "AAC" },
];
