"use client";
import { RadioButtonLarge } from "@/app/components/RadioButton";
import React, { useState, useEffect, useMemo, useContext } from "react";
import { useForm } from "react-hook-form";
import Heading from "@/app/components/Heading";
import {
  LabeledDropdown,
  MultiSelectDropdown,
} from "@/app/components/Dropdown";
import InputBox from "@/app/components/InputBox";
import Permissions from "@/app/components/Permissions";
import { DummyInputBoxWithLabelLightGray } from "@/app/components/DummyInputBox";
import { OutlinedButtonRed, SimpleButton } from "@/app/components/Buttons";
import axios from "axios";
import { GlobalContext } from "@/app/lib/GlobalContext";
import Image from "next/image";
import BulkUploadModal from "@/app/components/BulkUploadModal";
import NotificationFlag from "@/app/components/Notificationflag";

function EmployeeMaster({ setShowEmployeeForm, editEmployeeData }) {
  const {
    register,
    setValue,
    watch,
    handleSubmit,
    reset,
    formState: { errors },
    trigger,
  } = useForm();

  // Set initial state based on editEmployeeData
  const [demoRadio, setDemoRadio] = useState(
    editEmployeeData ? "Edit" : "Create"
  );
  const [resetFactor, setResetFactor] = useState(false);
  const [resetId, setResetId] = useState(false);
  const [employeeData, setEmployeeData] = useState(editEmployeeData || null);
  const [data, setData] = useState([]);
  const {
    server,
    setToggleCodeList,
    setCodeListConfig,
  } = useContext(GlobalContext);
  const [EmployeeReset, setEmployeeReset] = useState(false);
  const [autoGeneratedUserId, setAutoGeneratedUserId] = useState(null);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [showSuccessPopup, setShowSuccessPopup] = useState(false);
  const [createdEmployeeData, setCreatedEmployeeData] = useState(null);

  const [notification, setNotification] = useState({
    type: "success",
    message: "",
    visible: false,
  });

  const showNotification = (type, message) => {
    setNotification({ type, message, visible: true });
  };

  const userId = watch("userId");

  const defaultCheckboxState = {
    "title-Master (Administrative Control)": false,
    "permission-Export": false,
    "permission-Import": false,
    "permission-Entity Manager": false,
    "permission-Branch Master": false,
    "permission-Vendor Master": false,
    "permission-Customer": false,
    "permission-Employee Master": false,
    "permission-Tax Settings": false,
    "permission-Fuel Settings": false,
    "permission-Shipper Tariff": false,
    "permission-Shipper Tariff Bulk": false,
    "permission-Modify Shipper Tariff": false,
    "permission-Assign Customer & Target": false,
    "permission-Assign Sector": false,
    "permission-Custom Reports": false,
    "permission-KYC Verification": false,
    "permission-API Management": false,
    "permission-Service Master": false,
    "permission-Customer Discount": false,
    "permission-Delete Shipment": false,

    "title-Booking": false,
    "permission-Booking Deletion": false,
    "permission-AWB Entry": false,
    "permission-Digital Tally": false,
    "permission-Manifest": false,
    "permission-Hub Inscan (Client)": false,
    "permission-Quick Inscan": false,
    "permission-Manifest Close": false,
    "permission-Bulk Upload": false,
    "permission-RTO Shipment": false,
    "permission-Branch Manifest Report": false,
    "permission-International Pickup Order": false,
    "permission-Alert Messages": false,

    "title-Accounts": false,
    "permission-Accounts Deletion": false,
    "permission-Accounts Edit": false,
    "permission-Payment Entry": false,
    "permission-Credit Limit Temp": false,
    "permission-Acc-Account Ledger": false,
    "permission-Zone": false,
    "permission-Rate Sheet": false,
    "permission-Expense Entry": false,
    "permission-Amount Log": false,
    "permission-Credit Note": false,
    "permission-Debit Note": false,
    "permission-Claim For Lost Shipment": false,
    "permission-Discount Credit Note": false,
    "permission-Account Ledger Mail": false,
    "permission-Total Outstanding": false,
    "permission-Run Wise Sale Report": false,
    "permission-Payment Collection Report": false,
    "permission-ACC-Sale With Collection Report": false,
    "permission-Sale With Total Receiving": false,
    "permission-Booking Report With Amount": false,
    "permission-ACC-Credit Limit Report": false,
    "permission-ACC-Credit Limit Report With Days": false,
    "permission-ACC-Month Sale": false,
    "permission-New Sale Report": false,
    "permission-Payment Receipt Summary": false,
    "permission-Credit Summary Report": false,
    "permission-Debit Summary Report": false,
    "permission-Claim For Lost Shipment Summary": false,
    "permission-Discount Credit Note Summary": false,
    "permission-Payment Report": false,
    "permission-Payment Verification": false,
    "permission-Invoice Deletion": false,
    "permission-Suspense Account Access": false,
    "permission-FOC Account": false,
    "permission-Rate Calculator": false,

    "title-Operations": false,
    "permission-Operation Deletion": false,
    "permission-Run Entry": false,
    "permission-Clubbing": false,
    "permission-Bagging": false,
    "permission-Create Child Number": false,
    "permission-Run Transfer": false,
    "permission-Branch Bagging": false,
    "permission-Ops-Offload Shipment": false,
    "permission-Awb Print": false,
    "permission-Overseas Manifest": false,
    "permission-Bagging With Barcode": false,
    "permission-Child AWB No Report": false,
    "permission-Manifest Report": false,
    "permission-Manifest Report D": false,
    "permission-Club Report": false,
    "permission-Bag Report": false,
    "permission-EDI Report": false,
    "permission-Message Sheet": false,
    "permission-Custom Invoice": false,
    "permission-RTO Shipment Report": false,
    "permission-CSB V Report": false,
    "permission-Run Number Report": false,
    "permission-Run Process": false,

    "title-Labels": false,
    "permission-Label Page": false,
    "permission-AMS DPD": false,
    "permission-YYZ UPS": false,
    "permission-YVR UPS": false,
    "permission-UK DPD": false,
    "permission-CP": false,
    "permission-LHR FEDEX": false,
    "permission-Courier Please": false,

    "title-Billing": false,
    "permission-Billing Deletion": false,
    "permission-Billing Edit": false,
    "permission-Sales Report": false,
    "permission-AWB Billing": false,
    "permission-Invoice": false,
    "permission-Bulk Invoice": false,
    "permission-Bulk Invoice Delete": false,
    "permission-Invoice PTP": false,
    "permission-Upload IRN Number": false,
    "permission-Invoice Summary": false,
    "permission-Extra Charges": false,
    "permission-Email Invoice": false,
    "permission-Rate Hike": false,
    "permission-Data Lock": false,
    "permission-Auto Calculation": false,
    "permission-Sale Report With Hold": false,
    "permission-Bill-Sale With Collection Report": false,
    "permission-Bill-Credit Limit Report": false,
    "permission-Bill-Account Ledger": false,
    "permission-Bill-Credit Limit Report With Days": false,
    "permission-Sale Summary Sector Wise": false,
    "permission-Bill-Run Summary": false,
    "permission-Bill-Sale Report With Child Number": false,
    "permission-Bill-Month Sale": false,
    "permission-Credit Note Summary AWB No. Wise": false,
    "permission-Day Wise Sale": false,
    "permission-Invoice PTP Summary": false,

    "title-Customer Care": false,
    "permission-CC Deletion": false,
    "permission-CC Edit": false,
    "permission-Shipment Query": false,
    "permission-Register Complaint": false,
    "permission-Event Activity": false,
    "permission-Update Forwarding Number": false,
    "permission-POD Entry": false,
    "permission-POA Entry": false,
    "permission-POD Email": false,
    "permission-Message Circular": false,
    "permission-Portal Balance": false,
    "permission-Ticket Dashboard": false,
    "permission-CC-Offload Shipment": false,
    "permission-Tracking Report": false,
    "permission-Complaint Report": false,
    "permission-Client Report": false,
    "permission-Multiple Run Wise": false,
    "permission-Shipment Status Report": false,
    "permission-Child Shipment Status Report": false,
    "permission-Forwarding Number Report": false,
    "permission-CC-Run Summary": false,
    "permission-CC-Run Process": false,

    "title-Reports": false,
    "permission-Rep-Booking Report": false,
    "permission-Airwaybill Log": false,
    "permission-Booking With Sale": false,
    "permission-New Booking Report": false,
  };

  const [checkboxStates, setCheckboxStates] = useState(defaultCheckboxState);

  const permissionGroups = {
    "title-Master (Administrative Control)": [
      "permission-Export",
      "permission-Import",
      "permission-Entity Manager",
      "permission-Branch Master",
      "permission-Vendor Master",
      "permission-Customer",
      "permission-Employee Master",
      "permission-Tax Settings",
      "permission-Fuel Settings",
      "permission-Shipper Tariff",
      "permission-Shipper Tariff Bulk",
      "permission-Modify Shipper Tariff",
      "permission-Assign Customer & Target",
      "permission-Assign Sector",
      "permission-Custom Reports",
      "permission-KYC Verification",
      "permission-API Management",
      "permission-Service Master",
      "permission-Customer Discount",
      "permission-Delete Shipment",
    ],

    "title-Booking": [
      "permission-Booking Deletion",
      "permission-AWB Entry",
      "permission-Digital Tally",
      "permission-Manifest",
      "permission-Hub Inscan (Client)",
      "permission-Quick Inscan",
      "permission-Manifest Close",
      "permission-Bulk Upload",
      "permission-RTO Shipment",
      "permission-Branch Manifest Report",
      "permission-International Pickup Order",
      "permission-Alert Messages",
    ],

    "title-Accounts": [
      "permission-Accounts Deletion",
      "permission-Accounts Edit",
      "permission-Payment Entry",
      "permission-Credit Limit Temp",
      "permission-Acc-Account Ledger",
      "permission-Zone",
      "permission-Rate Sheet",
      "permission-Expense Entry",
      "permission-Amount Log",
      "permission-Credit Note",
      "permission-Debit Note",
      "permission-Account Ledger Mail",
      "permission-Claim For Lost Shipment",
      "permission-Discount Credit Note",
      "permission-Total Outstanding",
      "permission-Run Wise Sale Report",
      "permission-Payment Collection Report",
      "permission-ACC-Sale With Collection Report",
      "permission-Sale With Total Receiving",
      "permission-Booking Report With Amount",
      "permission-ACC-Credit Limit Report",
      "permission-ACC-Credit Limit Report With Days",
      "permission-ACC-Month Sale",
      "permission-New Sale Report",
      "permission-Payment Receipt Summary",
      "permission-Credit Summary Report",
      "permission-Debit Summary Report",
      "permission-Suspense Account Access",
      "permission-FOC Account",
      "permission-Rate Calculator",
    ],

    "title-Operations": [
      "permission-Operation Deletion",
      "permission-Run Entry",
      "permission-Clubbing",
      "permission-Bagging",
      "permission-Create Child Number",
      "permission-Run Transfer",
      "permission-Branch Bagging",
      "permission-Ops-Offload Shipment",
      "permission-Awb Print",
      "permission-Overseas Manifest",
      "permission-Bagging With Barcode",
      "permission-Child AWB No Report",
      "permission-Manifest Report",
      "permission-Manifest Report D",
      "permission-Club Report",
      "permission-Bag Report",
      "permission-EDI Report",
      "permission-Message Sheet",
      "permission-Custom Invoice",
      "permission-RTO Shipment Report",
      "permission-CSB V Report",
      "permission-Run Number Report",
      "permission-Run Process",
    ],

    "title-Labels": [
      "permission-Label Page",
      "permission-AMS DPD",
      "permission-YYZ UPS",
      "permission-YVR UPS",
      "permission-UK DPD",
      "permission-CP",
      "permission-Courier Please",

      "permission-LHR FEDEX",
    ],

    "title-Billing": [
      "permission-Billing Deletion",
      "permission-Billing Edit",
      "permission-Sales Report",
      "permission-AWB Billing",
      "permission-Invoice",
      "permission-Bulk Invoice",
      "permission-Bulk Invoice Delete",
      "permission-Invoice PTP",
      "permission-Upload IRN Number",
      "permission-Invoice Summary",
      "permission-Extra Charges",
      "permission-Email Invoice",
      "permission-Rate Hike",
      "permission-Data Lock",
      "permission-Auto Calculation",
      "permission-Sale Report With Hold",
      "permission-Bill-Sale With Collection Report",
      "permission-Bill-Credit Limit Report",
      "permission-Bill-Account Ledger",
      "permission-Bill-Credit Limit Report With Days",
      "permission-Sale Summary Sector Wise",
      "permission-Bill-Run Summary",
      "permission-Bill-Sale Report With Child Number",
      "permission-Bill-Month Sale",
      "permission-Credit Note Summary AWB No. Wise",
      "permission-Day Wise Sale",
      "permission-Invoice PTP Summary",
    ],

    "title-Customer Care": [
      "permission-CC Deletion",
      "permission-CC Edit",
      "permission-Shipment Query",
      "permission-Register Complaint",
      "permission-Event Activity",
      "permission-Update Forwarding Number",
      "permission-POD Entry",
      "permission-POA Entry",
      "permission-POD Email",
      "permission-Message Circular",
      "permission-Portal Balance",
      "permission-Ticket Dashboard",
      "permission-CC-Offload Shipment",
      "permission-Tracking Report",
      "permission-Complaint Report",
      "permission-Client Report",
      "permission-Multiple Run Wise",
      "permission-Shipment Status Report",
      "permission-Child Shipment Status Report",
      "permission-Forwarding Number Report",
      "permission-CC-Run Summary",
      "permission-CC-Run Process",
    ],

    "title-Reports": [
      "permission-Rep-Booking Report",
      "permission-Airwaybill Log",
      "permission-Booking With Sale",
      "permission-New Booking Report",
    ],
  };

  const departmentPermissionMap = {
    Sales: [
      "title-Operations",
      "title-Reports",
      "title-Customer Care",
      "title-Booking",
      "title-Accounts",
    ],
    Operations: ["title-Operations", "title-Booking", "title-Reports"],
    "Customer Support": [
      "title-Booking",
      "title-Operations",
      "title-Customer Care",
      "title-Reports",
    ],
    Account: [
      "title-Booking",
      "title-Operations",
      "title-Customer Care",
      "title-Reports",
      "title-Accounts",
      "title-Billing",
    ],
    Billing: [
      "title-Master (Administrative Control)",
      "title-Booking",
      "title-Accounts",
      "title-Operations",
      "title-Billing",
      "title-Customer Care",
      "title-Reports",
    ],
    "Sale Support": ["title-Booking", "title-Operations", "title-Accounts"],
    Management: [
      "title-Master (Administrative Control)",
      "title-Booking",
      "title-Accounts",
      "title-Operations",
      "title-Billing",
      "title-Customer Care",
      "title-Reports",
    ],
  };

  const departmentDashboardMap = {
    Operations: ["Operations"],
    Billing: ["Billing Employee"],
    Account: ["Collection HOD"],
    Sales: ["Sales"],
    Management: [
      "Revenue",
      "Sales",
      "Operations",
      "Sales HOD",
      "CS",
      "Collection HOD",
      "Billing Employee",
      "SS",
      "Counter Part",
      "Booking",
    ],
    Other: [""],
  };

  const toggleCheckboxState = (id) => {
    setCheckboxStates((prevStates) => {
      const newState = !prevStates[id];
      let updatedStates = { ...prevStates };

      if (id.startsWith("title-")) {
        const permissions = permissionGroups[id];
        updatedStates[id] = newState;
        permissions.forEach((perm) => {
          updatedStates[perm] = newState;
        });
      } else {
        updatedStates[id] = newState;

        Object.keys(permissionGroups).forEach((title) => {
          if (permissionGroups[title].includes(id)) {
            updatedStates[title] = permissionGroups[title].some(
              (perm) => updatedStates[perm]
            );
          }
        });
      }

      const selectedPermissions = Object.keys(updatedStates)
        .filter((key) => key.startsWith("permission-") && updatedStates[key])
        .map((key) => key.replace("permission-", ""));

      setValue("permissions", selectedPermissions);

      return updatedStates;
    });
  };

  // CONSOLIDATED: Load edit data when component mounts with editEmployeeData prop
  useEffect(() => {
    if (editEmployeeData) {
      console.log("Loading editEmployeeData:", editEmployeeData);

      setEmployeeData(editEmployeeData);
      setDemoRadio("Edit");

      // Update checkbox states based on edit data
      const updatedCheckboxStates = { ...defaultCheckboxState };
      if (editEmployeeData.permissions) {
        Object.keys(editEmployeeData.permissions).forEach((perm) => {
          const key = `permission-${perm}`;
          if (key in updatedCheckboxStates) {
            updatedCheckboxStates[key] = editEmployeeData.permissions[perm];
          }
        });

        // Update parent titles
        Object.entries(permissionGroups).forEach(([title, perms]) => {
          updatedCheckboxStates[title] = perms.some(
            (p) => updatedCheckboxStates[p]
          );
        });
      }

      setCheckboxStates(updatedCheckboxStates);

      // Update form with ALL edit data INCLUDING dashboard
      reset({
        userId: editEmployeeData.userId,
        email: editEmployeeData.email,
        userName: editEmployeeData.userName,
        password: editEmployeeData.password,
        role: editEmployeeData.role,
        branch: editEmployeeData.branch,
        department: editEmployeeData.department,
        hub: editEmployeeData.hub,
        dashboard: editEmployeeData.dashboardAccess || [],
      });

      // Extra safety: Set dashboard again after a brief delay
      setTimeout(() => {
        console.log(
          "Setting dashboard from editEmployeeData:",
          editEmployeeData.dashboardAccess
        );
        setValue("dashboard", editEmployeeData.dashboardAccess || []);
      }, 100);
    }
  }, [editEmployeeData]);

  // Reset when switching to Create mode
  useEffect(() => {
    if (demoRadio === "Create") {
      setResetFactor(!resetFactor);
      setCheckboxStates(defaultCheckboxState);
      reset({
        userId, // keep whatever user typed
        email: "",
        userName: "",
        password: "",
        role: "",
        branch: "",
        department: "",
        hub: "",
        dashboard: [],
      });

      setValue("branch", "");
      setValue("hub", "");
      setValue("department", "");
      handleRefresh();
    }
  }, [demoRadio]);

  // Fetch employee by userId in Edit mode (when manually entering userId)
  useEffect(() => {
    // Skip if we're in Create mode or if we already have editEmployeeData from props
    if (demoRadio === "Create" || (editEmployeeData && demoRadio === "Edit")) {
      return;
    }

    if (userId?.length !== 8) {
      reset({
        userId, // keep whatever user typed
        email: "",
        userName: "",
        password: "",
        role: "",
        branch: "",
        department: "",
        hub: "",
        dashboard: [],
      });

      setEmployeeData(null);
      setCheckboxStates(defaultCheckboxState);
      setResetFactor(!resetFactor);
      return;
    }

    const fetchEmployee = async () => {
      try {
        const { data } = await axios.get(
          `${server}/employee-master?userId=${userId}`
        );
        console.log("Fetched employee data:", data);

        setEmployeeData(data);

        const updatedCheckboxStates = { ...defaultCheckboxState };
        if (data.permissions) {
          Object.keys(data.permissions).forEach((perm) => {
            const key = `permission-${perm}`;
            if (key in updatedCheckboxStates) {
              updatedCheckboxStates[key] = data.permissions[perm];
            }
          });

          Object.entries(permissionGroups).forEach(([title, perms]) => {
            updatedCheckboxStates[title] = perms.some(
              (p) => updatedCheckboxStates[p]
            );
          });
        }

        setCheckboxStates(updatedCheckboxStates);

        // IMPORTANT: Include dashboard in the reset call!
        reset({
          userId: data.userId,
          email: data.email,
          userName: data.userName,
          password: data.password,
          role: data.role,
          branch: data.branch,
          department: data.department,
          hub: data.hub,
          dashboard: data.dashboardAccess || [],
        });

        // Extra safety: Set dashboard again
        setTimeout(() => {
          console.log(
            "Setting dashboard from fetched data:",
            data.dashboardAccess
          );
          setValue("dashboard", data.dashboardAccess || []);
        }, 100);
      } catch (err) {
        console.error("Failed to fetch employee:", err);
      }
    };
    fetchEmployee();
  }, [userId, demoRadio, editEmployeeData]);

  // Fetch next userId for Create mode
  useEffect(() => {
    if (demoRadio === "Create") {
      const fetchNextUserId = async () => {
        try {
          const { data } = await axios.get(`${server}/employee-master`);
          const lastEmployee = data[data.length - 1];
          let nextUserId = "11484000";
          if (lastEmployee && lastEmployee.userId) {
            const prevId = parseInt(lastEmployee.userId, 10);
            nextUserId = (prevId + 1).toString().padStart(8, "0");
          }
          setAutoGeneratedUserId(nextUserId);
          setValue("userId", nextUserId);
        } catch (err) {
          console.error("Failed to fetch next userId:", err);
          setAutoGeneratedUserId("11484000");
          setValue("userId", "11484000");
        }
      };
      fetchNextUserId();
    }
  }, [demoRadio, server, setValue]);

  const department = watch("department");

  // Auto-set permissions and dashboard based on department (Create mode only)
  useEffect(() => {
    if (!department) return;

    // ONLY run this logic in Create mode
    if (demoRadio === "Create") {
      console.log("Department changed in Create mode:", department);

      if (department === "Management") {
        setValue("role", "Admin");
      } else {
        setValue("role", "User");
      }

      const dashboard = departmentDashboardMap[department];
      if (dashboard) {
        console.log("Setting dashboard for department:", dashboard);
        setValue(
          "dashboard",
          Array.isArray(dashboard) ? dashboard : [dashboard]
        );
      }

      const selectedTitles = departmentPermissionMap[department] || [];
      let updated = { ...checkboxStates };

      Object.keys(updated).forEach((key) => {
        if (key.startsWith("permission-") || key.startsWith("title-")) {
          updated[key] = false;
        }
      });

      selectedTitles.forEach((titleKey) => {
        updated[titleKey] = true;
        permissionGroups[titleKey]?.forEach((perm) => {
          updated[perm] = true;
        });
      });

      setCheckboxStates(updated);
    }
    // In Edit mode, don't touch anything - data comes from editEmployeeData or fetch
  }, [department, demoRadio]);

  const onSubmit = async (data) => {
    console.log("Form submitted with data:", data);

    const allPermissions = Object.keys(checkboxStates).filter((key) =>
      key.startsWith("permission-")
    );

    const permissionsObject = {};
    allPermissions.forEach((permKey) => {
      const permName = permKey.replace("permission-", "");
      permissionsObject[permName] = checkboxStates[permKey];
    });

    const payload = {
      userId: data.userId,
      email: data.email,
      userName: data.userName,
      password: data.password,
      role: watch("role"),
      branch: watch("branch"),
      hub: watch("hub"),
      department: watch("department"),
      permissions: permissionsObject,
      dashboardAccess: Array.isArray(data.dashboard) ? data.dashboard : [],
    };

    if (demoRadio === "Create") {
      delete payload.userId;
    }

    console.log("Final payload:", payload);

    try {
      const stored = sessionStorage.getItem("user");
      const token = stored ? JSON.parse(stored) : null;

      let response;

      if (demoRadio === "Edit" && editEmployeeData) {
        response = await axios.put(`${server}/employee-master`, payload, {
          headers: { Authorization: `Bearer ${token?.userId}` },
        });
        showNotification("success", "Employee updated successfully!");
        handleRefresh();
        setValue("role", "");
        setValue("hub", "");
        setValue("branch", "");
        setValue("department", "");
      } else if (demoRadio === "Edit" && !editEmployeeData) {
        response = await axios.put(`${server}/employee-master`, payload, {
          headers: { Authorization: `Bearer ${token?.userId}` },
        });

        showNotification("success", "Employee updated successfully!");
        handleRefresh();
      } else if (demoRadio === "Create") {
        response = await axios.post(`${server}/employee-master`, payload, {
          headers: { Authorization: `Bearer ${token?.userId}` },
        });

        setCreatedEmployeeData(response.data.newEmployee);
        setShowSuccessPopup(true);
      }

      setResetFactor(!resetFactor);
      setResetId(!resetId);

      if (demoRadio !== "Create") {
        setCheckboxStates(defaultCheckboxState);
      }
    } catch (error) {
      console.error("Error submitting data:", error);
      showNotification("error", "Error saving employee. Please try again.");
    }
  };

  const handlePopupClose = () => {
    setShowSuccessPopup(false);
    setCreatedEmployeeData(null);
    setShowEmployeeForm(false);
  };

  const handleCopyCredentials = () => {
    if (createdEmployeeData) {
      const credentials = `User ID: ${createdEmployeeData.userId}\nPassword: ${createdEmployeeData.password
        }\nDepartment: ${createdEmployeeData.department}\nBranch: ${createdEmployeeData.branch
        }\nHub: ${createdEmployeeData.hub || createdEmployeeData.branch}`;
      navigator.clipboard.writeText(credentials).then(() => {
        showNotification("success", "Credentials copied to clipboard!");
      });
    }
  };

  const handleAction = async (action, rowData) => {
    if (action === "edit") {
      console.log("Edit action triggered for:", rowData);
    } else if (action === "delete") {
      const { code } = rowData;
      if (!code) {
        console.error("Code not found in rowData. Cannot delete.");
        return;
      }

      try {
        console.log("Delete action triggered for code:", code);
        const response = await axios.delete(`${server}/employee-master`, {
          params: { code },
        });
        console.log("Deletion successful:", response.data);
      } catch (error) {
        console.error(
          "Error during deletion:",
          error.response?.data || error.message
        );
      }
    }
  };

  const columns = useMemo(() => {
    const columnMapping = {
      "Employee Master": [
        { key: "userId", label: "User ID" },
        { key: "email", label: "Email" },
        { key: "branch", label: "Branch" },
        { key: "userName", label: "User Name" },
        { key: "password", label: "Password" },
        { key: "department", label: "Department" },
        { key: "role", label: "Role" },
      ],
    };

    return columnMapping["Employee Master"] || [];
  }, []);

  const handleRefresh = () => {
    setEmployeeReset(!EmployeeReset);
    setValue("role", "");
    setValue("hub", "");
    setValue("branch", "");
    setValue("department", "");
    setTimeout(() => {
      setValue("dashboard", []);
    }, 50);
  };

  const handleBulkUpload = () => {
    setShowUploadModal(true);
  };

  const handleBulkFileUpload = async (file) => {
    console.log("Bulk file selected:", file);

    const formData = new FormData();
    formData.append("file", file);

    try {
      const res = await axios.post(
        `${server}/employee-master/bulk-upload`,
        formData,
        {
          headers: { "Content-Type": "multipart/form-data" },
        }
      );

      console.log("Bulk upload success:", res.data);
      showNotification("success", "Bulk upload completed!");

      setShowUploadModal(false);
    } catch (err) {
      console.error(err);
      showNotification("error", "Bulk upload failed!");
    }
  };

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape") {
        setShowUploadModal(false);
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, []);

  // Debug: Watch dashboard value
  useEffect(() => {
    console.log("Dashboard value changed:", watch("dashboard"));
  }, [watch("dashboard")]);

  useEffect(() => {
    const fetchEmployees = async () => {
      try {
        const res = await axios.get(`${server}/employee-master`);
        setData(res.data || []);
      } catch (err) {
        console.error("Failed to fetch employees:", err);
        setData([]);
      }
    };

    fetchEmployees();
  }, [EmployeeReset]);

  const openCodeList = () => {
    setCodeListConfig({
      data,
      columns,
      name: "Employee Master",
      handleAction: (action, rowData) => {
        if (action === "edit") {
          setValue("userId", rowData.userId);
          setToggleCodeList(false);
          showNotification("success", `Employee ${rowData.userId} selected`);
        }
      },
    });

    setToggleCodeList(true);
  };

  return (
    <>
      <NotificationFlag
        type={notification.type}
        message={notification.message}
        visible={notification.visible}
        setVisible={(v) => setNotification({ ...notification, visible: v })}
      />
      <form className="flex flex-col gap-9" onSubmit={handleSubmit(onSubmit)}>
        <div className="flex gap-3 items-center text-center">
          <span
            onClick={() => {
              setShowEmployeeForm(false);
            }}
            className="cursor-pointer mt-1"
          >
            <Image
              src="./back-filled.svg"
              alt="back_arrow"
              width={15}
              height={13}
            />
          </span>
          <Heading
            title="Employee Master"
            onRefresh={handleRefresh}
            onClickBulkUploadBtn={handleBulkUpload}
            onClickCodeList={openCodeList}
          />
          {showUploadModal && (
            <BulkUploadModal
              title="Bulk Upload Employees"
              onClose={() => setShowUploadModal(false)}
              onFileUpload={handleBulkFileUpload}
              sampleFileLink="/employee-sample.xlsx"
              setVisible={() => { }}
            />
          )}
        </div>

        <div className="flex w-full gap-3 justify-between">
          <div className="flex  gap-3">
            <RadioButtonLarge
              id={`Create`}
              label={`Create`}
              name={`demo`}
              register={register}
              setValue={setValue}
              selectedValue={demoRadio}
              setSelectedValue={setDemoRadio}
            />
            <RadioButtonLarge
              id={`Edit`}
              label={`Edit`}
              name={`demo`}
              register={register}
              setValue={setValue}
              selectedValue={demoRadio}
              setSelectedValue={setDemoRadio}
            />
          </div>

          <div className="">
            <div className=" flex gap-3">
              <div className="w-[190px]">
                <LabeledDropdown
                  options={["User", "Admin", "Branch User", "Counter Part"]}
                  register={register}
                  setValue={setValue}
                  value="role"
                  title="Role"
                  selectedValue={watch("role")}
                  error={errors.role}
                  validation={{
                    required: "Role is required",
                  }}
                  resetFactor={EmployeeReset}
                />
              </div>
              <div className="w-[16vw]">
                <MultiSelectDropdown
                  options={[
                    "Revenue",
                    "Sales",
                    "Operations",
                    "Sales HOD",
                    "CS",
                    "Collection HOD",
                    "Billing Employee",
                    "SS",
                    "Counter Part",
                    "Booking",
                  ]}
                  selected={
                    Array.isArray(watch("dashboard"))
                      ? watch("dashboard")
                      : editEmployeeData?.dashboardAccess || []
                  }
                  onChange={(val) => setValue("dashboard", val)}
                  placeholder="Dashboard"
                />
              </div>
            </div>
          </div>
        </div>

        <div className="flex justify-between w-full">
          <div className="flex flex-col gap-6 w-full">
            <div className="flex gap-9 w-full">
              <div className="flex flex-col gap-3 w-full">
                {demoRadio === "Edit" && (
                  <InputBox
                    placeholder="User ID"
                    register={register}
                    setValue={setValue}
                    value="userId"
                    // initialValue={employeeData?.userId || ""}
                    initialValue={watch("userId")}
                    resetFactor={EmployeeReset}
                    error={errors.userId}
                    validation={{
                      required: "User ID is required",
                    }}
                  />
                )}
                {demoRadio === "Create" && (
                  <DummyInputBoxWithLabelLightGray
                    label="User ID"
                    register={register}
                    setValue={setValue}
                    value="userId"
                    watch={watch}
                    placeholder={autoGeneratedUserId || "Loading..."}
                    error={errors.userId}
                    validation={{
                      required: "User ID is required",
                    }}
                  />
                )}

                <InputBox
                  resetFactor={EmployeeReset}
                  placeholder="Email"
                  register={register}
                  setValue={setValue}
                  value="email"
                  // initialValue={employeeData?.email || ""}
                  initialValue={watch("email")}
                  error={errors.email}
                  trigger={trigger}
                  validation={{
                    required: "Email is required",
                    pattern: {
                      value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                      message: "Invalid email format",
                    },
                  }}
                />

                <LabeledDropdown
                  resetFactor={EmployeeReset}
                  options={["Delhi", "Mumbai", "Ahemdabad"]}
                  register={register}
                  setValue={setValue}
                  value="branch"
                  title="Branch"
                  // defaultValue={employeeData?.branch || ""}
                  defaultValue={watch("branch")}
                  error={errors.branch}
                  validation={{
                    required: "Branch is required",
                  }}
                />

                <LabeledDropdown
                  resetFactor={EmployeeReset}
                  options={["Delhi", "Mumbai", "Ahemdabad"]}
                  register={register}
                  setValue={setValue}
                  value="hub"
                  title="Hub"
                  // defaultValue={employeeData?.hub || ""}
                  defaultValue={watch("hub")}
                  error={errors.hub}
                  validation={{
                    required: "hub is required",
                  }}
                />
              </div>

              <div className="flex flex-col gap-3 w-full">
                <InputBox
                  resetFactor={EmployeeReset}
                  placeholder="User Name"
                  register={register}
                  setValue={setValue}
                  value="userName"
                  trigger={trigger}
                  // initialValue={employeeData?.userName || ""}
                  initialValue={watch("userName")}
                  error={errors.userName}
                  validation={{
                    required: "User Name is required",
                    minLength: {
                      value: 3,
                      message: "Minimum 3 characters required",
                    },
                  }}
                />

                <InputBox
                  resetFactor={EmployeeReset}
                  placeholder="Password"
                  register={register}
                  setValue={setValue}
                  value="password"
                  trigger={trigger}
                  // initialValue={employeeData?.password || ""}
                  initialValue={watch("password")}
                  error={errors.password}
                  validation={{
                    required: "Password is required",
                    minLength: {
                      value: 6,
                      message: "Password must be at least 6 characters",
                    },
                  }}
                />

                <LabeledDropdown
                  resetFactor={EmployeeReset}
                  options={[
                    "Sales",
                    "Operations",
                    "Customer Support",
                    "Account",
                    "Billing",
                    "Collection",
                    "Counterpart",
                    "Sale Support",
                    "Management",
                    "Other",
                  ]}
                  register={register}
                  setValue={setValue}
                  value="department"
                  title="Department"
                  // defaultValue={employeeData?.department || ""}
                  defaultValue={watch("department")}
                  error={errors.department}
                  validation={{
                    required: "Department is required",
                  }}
                />
                <div className="w-full  flex justify-end">
                  <div className="w-[20%]">
                    <SimpleButton
                      name={demoRadio === "Create" ? "Save" : "Update"}
                      type="submit"
                    />
                  </div>
                </div>
              </div>
            </div>

            <div>
              <Permissions
                register={register}
                setValue={setValue}
                checkboxStates={checkboxStates}
                setCheckboxStates={setCheckboxStates}
                toggleCheckboxState={toggleCheckboxState}
                permissionGroups={permissionGroups}
              />
            </div>
          </div>
        </div>
      </form>

      {/* Success Popup */}
      {showSuccessPopup && createdEmployeeData && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 ">
          <div className="bg-white rounded-lg shadow-lg max-w-md w-[496px] mx-4">
            {/* Header */}
            <div className="bg-red-500 text-white px-9 py-3 rounded-t-lg bg-red flex flex-col gap-1 items-center justify-center">
              <h2 className="text-3xl font-semibold text-white">
                New Employee Created!
              </h2>
              <p className="text-base opacity-90">
                Share the following credentials with the{" "}
                <span className="font-bold">
                  {createdEmployeeData.userName}
                </span>
              </p>
            </div>

            {/* Body */}
            <div className="flex p-6 gap-10">
              <div className="flex flex-col gap-2">
                <span className="text-base text-[#EA1B40] font-medium">
                  User ID
                </span>
                <span className="text-base text-[#EA1B40] font-medium">
                  User Name
                </span>
                <span className="text-base text-[#EA1B40] font-medium">
                  Password
                </span>
                <span className="text-base text-[#EA1B40] font-medium">
                  Department
                </span>
                <span className="text-base text-[#EA1B40] font-medium">
                  Branch
                </span>
                <span className="text-base text-[#EA1B40] font-medium">
                  Hub
                </span>
              </div>

              <div className="flex flex-col gap-2">
                <span className="text-base font-medium">
                  {createdEmployeeData.userId}
                </span>
                <span className="text-base font-medium">
                  {createdEmployeeData.userName}
                </span>
                <span className="text-base font-medium">
                  {createdEmployeeData.password}
                </span>
                <span className="text-base font-medium">
                  {createdEmployeeData.department}
                </span>
                <span className="text-base font-medium">
                  {createdEmployeeData.branch}
                </span>
                <span className="text-base font-medium">
                  {createdEmployeeData.hub || createdEmployeeData.branch}
                </span>
              </div>
            </div>

            <div className="flex gap-4 justify-center mb-2">
              <div>
                <OutlinedButtonRed label={"Close"} onClick={handlePopupClose} />
              </div>
              <div>
                <SimpleButton
                  name={"Copy Credentials"}
                  onClick={handleCopyCredentials}
                />
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

export default EmployeeMaster;
